### ISSUE TITLE
PMS repo update

### ISSUE THREAD

**Issue by dcop** [linuxserver/docker-plex-armhf#6]
Hi there,

I noticed you switched to ubuntu xenial as base image and since xenial is based on stretch, would it be ok to just s/jessie/stretch in Dockerfile? Instructions on https://dev2day.de/plex-media-server-arm/ are also using updated version.

Thanks

**Comment by j0nnymoe** [comment]
We wouldn't be moving our base image away from ubuntu for this unfortunately.
