### ISSUE TITLE
Support pulling synology version

### ISSUE THREAD

**Issue by amondit** [linuxserver/docker-plex-armhf#7]
Hello, and thanks for the good work you're doing building all these images!

I am trying to deploy this plex-armhf image on my arm box (s812 soc). It is a correct armv7 box:

`# cat /proc/cpuinfo`
`processor	: 0`
`model name	: ARMv7 Processor rev 1 (v7l)`
`BogoMIPS	: 190.97`
`Features	: half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32`
`CPU implementer	: 0x41`
`CPU architecture: 7`
`CPU variant	: 0x4`
`CPU part	: 0xc09`
`CPU revision	: 1`
`...`

You see that it hasn't vfpv4 or idiva, but still is armv7 with vfpv3, so should be compatible with armhf?

But when I deploy this plex-armhf image I get `Illegal Instructions` error on the plex container, trying to run plex.

Having looked a bit, it seems that the plexmediaserver-installer is, at runtime (so image buildtime on your jenkins server), it looks at the CPU capabilities to fetch the netgear (if vfp4, neon and idiva are supported, or architecture v8) or synology (otherwise) binary (see [plexmediaserver-installer script](https://github.com/uglymagoo/plexmediaserver-installer/blob/master/DEBIAN/postinst#L18))

If you have a look at your [latest plex-armhf build](https://ci.linuxserver.io/job/Docker-Builders/job/armhf/job/armhf-plex/117/console) in jenkins, you can see in the console output the `Downloading readynas package ...` log entry, meaning it's downloading the netgear one based on your build server capabilities.

But on my box, I would like to run the regular synology armv7 one, otherwise I'll get these Illegal Instructions issues.

Could it be possible that the build pipeline build this version as well?

Thanks,

**Comment by sparklyballs** [comment]
it would probably be easier if you cloned the git repo and built the image locally.
